import { Ticket, AppConfig } from './types';

export const INITIAL_CONFIG: AppConfig = {
  brandTone: 'Friendly',
  toneDescription: 'Sound like a calm, knowledgeable friend. Keep replies short but empathetic. Use active voice.',
  knowledgeContext: `
    QueueSense supports SSO (Single Sign-On) for Enterprise plans only.
    Billing cycles renew on the 1st of the month.
    API rate limits are 1000 requests per minute for Pro users.
    To reset a password, users must click "Forgot Password" on the login screen.
    We do not support Internet Explorer 11.
  `.trim(),
};

export const MOCK_TICKETS: Ticket[] = [
  {
    id: '#TICK00149',
    subject: 'Login failing for SSO users',
    body: 'Hi, our team is trying to log in via Okta but we are getting a 403 error. This started happening about an hour ago. We recently upgraded to the Enterprise plan. Please help ASAP as nobody can work.',
    status: 'Escalated',
    priority: 'High',
    category: 'Authentication',
    customer: {
      id: 'c1',
      name: 'Alice Johnson',
      company: 'Acme Corp',
      plan: 'Enterprise',
      mrr: 5000,
      isHighValue: true,
      joinedAt: '2022-03-10',
    },
    assignedAgent: {
      id: 'a1',
      name: 'Sam Patel',
      avatarUrl: 'https://picsum.photos/seed/agent1/64/64',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    aiSummary: 'Customer cannot log in with SSO after plan upgrade.',
  },
  {
    id: '#TICK00150',
    subject: 'Invoice for March is incorrect',
    body: 'Hello, I see a charge for $1200 but my plan should be $999. Can you explain the difference?',
    status: 'Open',
    priority: 'Medium',
    category: 'Billing',
    customer: {
      id: 'c2',
      name: 'Bob Smith',
      company: 'TechStart Inc',
      plan: 'Pro',
      mrr: 999,
      isHighValue: false,
      joinedAt: '2023-01-15',
    },
    assignedAgent: {
      id: 'a2',
      name: 'Sarah Lee',
      avatarUrl: 'https://picsum.photos/seed/agent2/64/64',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    aiSummary: 'Customer questioning invoice amount discrepancy.',
  },
  {
    id: '#TICK00151',
    subject: 'Feature Request: Dark Mode',
    body: 'Is there any plan to add dark mode? My eyes hurt working late at night.',
    status: 'Pending',
    priority: 'Low',
    category: 'Feature Request',
    customer: {
      id: 'c3',
      name: 'Charlie Davis',
      company: 'DesignFlow',
      plan: 'Starter',
      mrr: 49,
      isHighValue: false,
      joinedAt: '2023-06-20',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    aiSummary: 'User requesting dark mode feature.',
  },
  {
    id: '#TICK00152',
    subject: 'API returning 500 errors',
    body: 'Our integration script is failing with internal server errors on the /users endpoint. Here is the request ID: req_123xyz.',
    status: 'Open',
    priority: 'High',
    category: 'API',
    customer: {
      id: 'c4',
      name: 'Dana White',
      company: 'MegaStream',
      plan: 'Enterprise',
      mrr: 12000,
      isHighValue: true,
      joinedAt: '2021-11-05',
    },
    assignedAgent: {
      id: 'a1',
      name: 'Sam Patel',
      avatarUrl: 'https://picsum.photos/seed/agent1/64/64',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    aiSummary: '500 errors reported on /users API endpoint.',
  },
  {
    id: '#TICK00153',
    subject: 'How do I invite team members?',
    body: 'I just signed up and cant find the invite button. The documentation link seems broken.',
    status: 'Open',
    priority: 'Low',
    category: 'Onboarding',
    customer: {
      id: 'c5',
      name: 'Evan Wright',
      company: 'SoloDev',
      plan: 'Starter',
      mrr: 29,
      isHighValue: false,
      joinedAt: '2023-10-01',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    aiSummary: 'New user unable to find team invite function.',
  },
  {
    id: '#TICK00154',
    subject: 'Upgrade to Enterprise',
    body: 'We are growing fast and need to discuss custom pricing and SSO. Who can I talk to?',
    status: 'In Progress',
    priority: 'Medium',
    category: 'Sales',
    customer: {
      id: 'c6',
      name: 'Fiona Green',
      company: 'GrowFast',
      plan: 'Pro',
      mrr: 400,
      isHighValue: false,
      joinedAt: '2023-02-14',
    },
    assignedAgent: {
      id: 'a3',
      name: 'Mike Ross',
      avatarUrl: 'https://picsum.photos/seed/agent3/64/64',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    aiSummary: 'Customer inquiring about Enterprise upgrade.',
  },
  {
    id: '#TICK00155',
    subject: 'Bug: Images not loading',
    body: 'Images in the gallery view are showing as broken links for my customers.',
    status: 'Open',
    priority: 'High',
    category: 'Bug',
    customer: {
      id: 'c7',
      name: 'Greg House',
      company: 'MediClick',
      plan: 'Pro',
      mrr: 800,
      isHighValue: false,
      joinedAt: '2022-08-22',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    aiSummary: 'Broken image links reported in gallery view.',
  },
  {
    id: '#TICK00156',
    subject: 'Account suspension warning?',
    body: 'I got an email saying my account is at risk due to payment failure. I updated my card. Is everything okay now?',
    status: 'Resolved',
    priority: 'High',
    category: 'Billing',
    customer: {
      id: 'c8',
      name: 'Hannah Montana',
      company: 'Star Inc',
      plan: 'Pro',
      mrr: 500,
      isHighValue: false,
      joinedAt: '2023-05-30',
    },
    assignedAgent: {
      id: 'a2',
      name: 'Sarah Lee',
      avatarUrl: 'https://picsum.photos/seed/agent2/64/64',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    aiSummary: 'Customer confirming payment method update.',
  },
  {
    id: '#TICK00157',
    subject: 'GDPR Data Deletion Request',
    body: 'Please delete all data associated with our workspace as we are closing the company.',
    status: 'Pending',
    priority: 'Medium',
    category: 'Legal',
    customer: {
      id: 'c9',
      name: 'Ian Somerhalder',
      company: 'Vamp Diaries',
      plan: 'Starter',
      mrr: 99,
      isHighValue: false,
      joinedAt: '2021-01-01',
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    aiSummary: 'Request for GDPR data deletion.',
  }
];
